buildingsInfo = [
    {'buildingId': '1800-6-ave-blitman-hall', 'roomNum': 36958939, 'friendlyNames': ['blitman', 'blitman hall', 'blitman dorm']},
    {'buildingId': '384-congress-st-polytech', 'roomNum': 36958940, 'friendlyNames': ['polytech', 'polytech apartments']},
    {'buildingId': 'barh-central-fl-1', 'roomNum': 369589058, 'friendlyNames': ['barh','bar h','burdett', 'barh dorm', 'bar h dorm', 'burdett avenue residence hall', 'burdett avenue', 'burdett ave']},
    {'buildingId': 'barton-hall-2-floor', 'roomNum': 3695891, 'friendlyNames': ['barton', 'barton dorm', 'barton hall']},
    {'buildingId': 'bray-hall-basement', 'roomNum': 3695892, 'friendlyNames': ['bray', 'bray hall', 'bray dorm']},
    {'buildingId': 'brinsmade-1-floor', 'roomNum': 3695893, 'friendlyNames': ['brinsmade', 'brinsmade apartments']},
    {'buildingId': 'bryckwyck-a-basement', 'roomNum': 3695894, 'friendlyNames': ['bryckwyck a']},
    {'buildingId': 'bryckwyck-b-basement', 'roomNum': 36958932, 'friendlyNames': ['bryckwyck b']},
    {'buildingId': 'bryckwyck-c-basement ', 'roomNum': 36958933, 'friendlyNames': ['bryckwyck c']},
    {'buildingId': 'bryckwyck-d-basement', 'roomNum': 36958934, 'friendlyNames': ['bryckwyck d']},
    {'buildingId': 'bryckwyck-f-basement', 'roomNum': 36958935, 'friendlyNames': ['bryckwyck f']},
    {'buildingId': 'bryckwyck-g-basement', 'roomNum': 36958936, 'friendlyNames': ['bryckwyck g']},
    {'buildingId': 'burdett-barh-b-2-fl', 'roomNum': 3695896, 'friendlyNames': ['burdett b', 'barh b', 'bar h b']},
    {'buildingId': 'burdett-barh-c-2-fl', 'roomNum': 3695897, 'friendlyNames': ['burdett c', 'barh c', 'bar h c']},
    {'buildingId': 'burdett-hall-barh-a-fl-1', 'roomNum': 3695895, 'friendlyNames': ['burdett a floor one', 'barh a floor one', 'bar h a floor one', 'burdett a first floor', 'barh a first floor', 'bar h a first floor']},
    {'buildingId': 'burdett-hall-barh-a-fl-2', 'roomNum': 36958945, 'friendlyNames': ['burdett a floor two', 'barh a floor two', 'bar h a floor two', 'burdett a second floor', 'barh a second floor', 'bar h a second floor']},
    {'buildingId': 'burdett-hall-barh-d-fl-1', 'roomNum': 3695898, 'friendlyNames': ['burdett d floor one', 'barh d floor one', 'bar h d floor one', 'burdett d first floor', 'barh d first floor', 'bar h d first floor']},
    {'buildingId': 'burdett-hall-barh-d-fl-2', 'roomNum': 36958946, 'friendlyNames': ['burdett d floor two', 'barh d floor two', 'bar h d floor two', 'burdett d second floor', 'barh d second floor', 'bar h d second floor']},
    {'buildingId': 'cary-hall-basement', 'roomNum': 3695899, 'friendlyNames': ['cary', 'cary hall', 'cary dorm']},
    {'buildingId': 'colonie-apts-a-1-floor', 'roomNum': 36958910, 'friendlyNames': ['colonie a']},
    {'buildingId': 'colonie-apts-b-1-floor', 'roomNum': 36958911, 'friendlyNames': ['colonie b']},
    {'buildingId': 'colonie-apts-c-1-floor', 'roomNum': 36958912, 'friendlyNames': ['colonie c']},
    {'buildingId': 'colonie-apts-d-1-floor', 'roomNum': 36958913, 'friendlyNames': ['colonie d']},
    {'buildingId': 'colvin-1-floor', 'roomNum': 36958914, 'friendlyNames': ['colvin', 'colvin apartments']},
    {'buildingId': 'crockett-hall-basement', 'roomNum': 36958915, 'friendlyNames': ['crockett', 'crockett hall', 'crockett dorm']},
    {'buildingId': 'davison-hall-basement', 'roomNum': 36958931, 'friendlyNames': ['davison', 'davison hall', 'davison dorm']},
    {'buildingId': 'e-dorms-basement', 'roomNum': 36958917, 'friendlyNames': ['e', 'e complex']},
    {'buildingId': 'hall-hall-basement', 'roomNum': 36958918, 'friendlyNames': ['hall', 'hall hall', 'hall squared', 'hall dorm']},
    {'buildingId': 'hunt-quad-basement', 'roomNum': 36958937, 'friendlyNames': ['hunt', 'hunt hall', 'hunt dorm', 'quad hunt', 'quad', 'quad one', 'quad two']},
    {'buildingId': 'nason-hall-basement', 'roomNum': 36958920, 'friendlyNames': ['nason', 'nason hall', 'nason dorm']},
    {'buildingId': 'north-hall-1 floor', 'roomNum': 36958921, 'friendlyNames': ['north', 'north hall', 'north dorm']},
    {'buildingId': 'nugent-hall-lobby', 'roomNum': 36958930, 'friendlyNames': ['nugent', 'nugent hall', 'nugent dorm']},
    {'buildingId': 'sharp-hall-basement', 'roomNum': 36958922, 'friendlyNames': ['sharp', 'sharp hall', 'sharp dorm']},
    {'buildingId': 'stackwyck-rousseau-1-floor', 'roomNum': 36958926, 'friendlyNames': ['stackwyck rousseau', 'rousseau']},
    {'buildingId': 'stackwyck-thompson-1-floor', 'roomNum': 36958925, 'friendlyNames': ['stackwyck thompson', 'thompson']},
    {'buildingId': 'stackwyck-williams-1-floor', 'roomNum': 36958927, 'friendlyNames': ['stackwyck williams', 'williams']},
    {'buildingId': 'stackwyck-wiltsie-1-floor', 'roomNum': 36958924, 'friendlyNames': ['stackwyck wiltsie', 'wiltsie']},
    {'buildingId': 'warren-hall-basement', 'roomNum': 36958928, 'friendlyNames': ['warren','warren hall', 'warren dorm']}
]
