buildingsInfo = [
    {'buildingId': '1800 6 ave-blitman hall', 'roomNum': 36958939, 'friendlyNames': ['Blitman', 'Blitman Hall', 'Blitman Dorm']},
    {'buildingId': '384 congress st-polytech', 'roomNum': 36958940, 'friendlyNames': ['Polytech', 'Polytech Apartments']},
    {'buildingId': 'barh-central fl 1', 'roomNum': 369589058, 'friendlyNames': []},
    {'buildingId': 'barton hall-2 floor ', 'roomNum': 3695891, 'friendlyNames': []},
    {'buildingId': 'bray hall-basement', 'roomNum': 3695892, 'friendlyNames': []},
    {'buildingId': 'brinsmade-1 floor', 'roomNum': 3695893, 'friendlyNames': []},
    {'buildingId': 'bryckwyck (a)-basement', 'roomNum': 3695894, 'friendlyNames': []},
    {'buildingId': 'bryckwyck (b)-basement', 'roomNum': 36958932, 'friendlyNames': []},
    {'buildingId': 'bryckwyck (c)-basement ', 'roomNum': 36958933, 'friendlyNames': []},
    {'buildingId': 'bryckwyck (d)-basement', 'roomNum': 36958934, 'friendlyNames': []},
    {'buildingId': 'bryckwyck (f)-basement', 'roomNum': 36958935, 'friendlyNames': []},
    {'buildingId': 'bryckwyck (g)-basement', 'roomNum': 36958936, 'friendlyNames': []},
    {'buildingId': 'burdett (barh) (b) 2fl', 'roomNum': 3695896, 'friendlyNames': []},
    {'buildingId': 'burdett (barh) (c) 2 fl', 'roomNum': 3695897, 'friendlyNames': []},
    {'buildingId': 'burdett hall-barh a fl 1', 'roomNum': 3695895, 'friendlyNames': []},
    {'buildingId': 'burdett hall-barh a fl 2', 'roomNum': 36958945, 'friendlyNames': []},
    {'buildingId': 'burdett hall-barh d fl 1', 'roomNum': 3695898, 'friendlyNames': []},
    {'buildingId': 'burdett hall-barh d fl 2', 'roomNum': 36958946, 'friendlyNames': []},
    {'buildingId': 'cary hall-basement', 'roomNum': 3695899, 'friendlyNames': []},
    {'buildingId': 'colonie apts (a)-1 floor', 'roomNum': 36958910, 'friendlyNames': []},
    {'buildingId': 'colonie apts (b)-1 floor', 'roomNum': 36958911, 'friendlyNames': []},
    {'buildingId': 'colonie apts (c)-1 floor', 'roomNum': 36958912, 'friendlyNames': []},
    {'buildingId': 'colonie apts (d)-1 floor', 'roomNum': 36958913, 'friendlyNames': []},
    {'buildingId': 'colvin-1 floor', 'roomNum': 36958914, 'friendlyNames': []},
    {'buildingId': 'crockett hall-basement', 'roomNum': 36958915, 'friendlyNames': []},
    {'buildingId': 'davison hall-basement', 'roomNum': 36958931, 'friendlyNames': []},
    {'buildingId': 'e dorms-basement', 'roomNum': 36958917, 'friendlyNames': []},
    {'buildingId': 'hall hall-basement', 'roomNum': 36958918, 'friendlyNames': []},
    {'buildingId': 'hunt quad-basement', 'roomNum': 36958937, 'friendlyNames': []},
    {'buildingId': 'nason hall-basement', 'roomNum': 36958920, 'friendlyNames': []},
    {'buildingId': 'north hall-1 floor', 'roomNum': 36958921, 'friendlyNames': []},
    {'buildingId': 'nugent hall-lobby', 'roomNum': 36958930, 'friendlyNames': []},
    {'buildingId': 'sharp hall-basement', 'roomNum': 36958922, 'friendlyNames': []},
    {'buildingId': 'stackwyck-rousseau 1 floor', 'roomNum': 36958926, 'friendlyNames': []},
    {'buildingId': 'stackwyck-thompson 1 floor', 'roomNum': 36958925, 'friendlyNames': []},
    {'buildingId': 'stackwyck-williams 1 floor', 'roomNum': 36958927, 'friendlyNames': []},
    {'buildingId': 'stackwyck-wiltsie 1 floor', 'roomNum': 36958924, 'friendlyNames': []},
    {'buildingId': 'warren hall-basement', 'roomNum': 36958928, 'friendlyNames': []}]
